### PR TITLE
Fix how jruby parses bytes from protobuf

### PR DESCRIPTION
**Pull request by rc-rwardin**
This should fix the issues we're seeing when trying to parse bytes from protobuf.

### CODE REVIEW

**Review by nickriemondi — APPROVED** [review]
🎉

**Review by ebrohman — COMMENTED** [review]
Nice

**Comment by AlexanderDewhirst** [comment]
Yea this is really cool!

**Comment by CodingAnarchy** [comment]
@rc-rwardin Any plans to submit this fix upstream, or is it something that is unique to our use case?

**Comment by rc-rwardin** [comment]
@CodingAnarchy Not 100% sure if it should be submitted upstream, as it does break the default field for bytes (and it's corresponding test). Additionally, this is for jruby specific and they're still working on adding back jruby into the build process.

**Pull request merged**
